version : '3.9'

services :
  
    generator:
      build: .
        ports:
          - "5000:5000"
        volumes:
          - .:/code
        environment:
          FLASK_ENV: development
    solver:
      image : python:3.7-alpine
      build: .
